### ISSUE TITLE
Caching multiple modules at once

### ISSUE THREAD

**Issue by pixeleet** [danilo-valente/compy#2]
The behaviour was changed in #1 but I believe that change caused more to change than intended.
Opening this issue a discussion placeholder.

**Comment by danilo-valente** [comment]
In fact, the code changed the behaviour of all native commands because they were all wrappers around the `buildCommand` function. Not to worry tho, because I refactored it to apply only to `cache`, `fmt`, `lint` and `test` commands. You can check it out [here](https://github.com/danilo-valente/compy/commit/121e171fbcdac5ae6763ce5cd10e6f4eab51f109).

**Comment by danilo-valente** [comment]
But I'm also curious about your use cases for Compy and some possible improvements or new features that you think would worth implementing, if you could share a little bit.

**Comment by pixeleet** [comment]
I started using it as a tool for managing a monorepo like structure in a Deno project.

**Comment by danilo-valente** [comment]
Great to hear that. I've just release a new version with the latest changes, including the ones discussed here.
I'm closing this issue for now, but please let me know if you have any suggestions that I'd be glad to address them.
